# Generated by Django 4.1.4 on 2023-04-02 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_remove_item_id_remove_map_id_alter_item_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='map',
        ),
        migrations.AddField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='maps.map'),
            preserve_default=False,
        ),
    ]
