# Generated by Django 4.1.4 on 2023-04-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_alter_map_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
