# Generated by Django 4.1.4 on 2023-01-10 22:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], default='Homme', max_length=50)),
                ('birth_date', models.IntegerField()),
                ('death_date', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('is_living', models.BooleanField(default=True)),
                ('is_player', models.BooleanField(default=False)),
                ('is_native', models.BooleanField(default=False)),
                ('vassal', models.CharField(max_length=255)),
                ('fiche', models.CharField(max_length=255, null=True)),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_father', to='lineage.character')),
                ('heirs', models.ManyToManyField(related_name='_heirs', to='lineage.character')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_mother', to='lineage.character')),
                ('spouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_spouse', to='lineage.character')),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lineage.character')),
            ],
        ),
    ]
