# Generated by Django 4.1.4 on 2023-01-10 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lineage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='birth_date',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='death_date',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='father',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='_father', to='lineage.character'),
        ),
        migrations.AlterField(
            model_name='character',
            name='fiche',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='character',
            name='mother',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='_mother', to='lineage.character'),
        ),
        migrations.AlterField(
            model_name='character',
            name='spouse',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='_spouse', to='lineage.character'),
        ),
        migrations.AlterField(
            model_name='character',
            name='status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='character',
            name='vassal',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
