# Generated by Django 4.1.4 on 2023-01-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineage', '0003_alter_character_heirs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='birth_date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='death_date',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
