# Generated by Django 4.1.4 on 2023-01-10 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lineage', '0004_alter_character_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_father', to='lineage.character'),
        ),
        migrations.AlterField(
            model_name='character',
            name='fiche',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='heirs',
            field=models.ManyToManyField(blank=True, null=True, related_name='_heirs', to='lineage.character'),
        ),
        migrations.AlterField(
            model_name='character',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_mother', to='lineage.character'),
        ),
        migrations.AlterField(
            model_name='character',
            name='spouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_spouse', to='lineage.character'),
        ),
        migrations.AlterField(
            model_name='character',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='vassal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
