# Generated by Django 4.1.4 on 2023-02-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineage', '0006_alter_character_heirs'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
