# Generated by Django 4.1.4 on 2023-03-05 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineage', '0007_character_full_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['-last_name']},
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'ordering': ['-created']},
        ),
    ]
