# Generated by Django 4.1 on 2022-12-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pantheon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('group', models.CharField(blank=True, choices=[('Groupe', 'Groupe'), ('Milice(ne)', 'Milice'), ('Habitant(e)', 'Peuple'), ('Noble', 'Noblesse'), ('Prêtre(sse)', 'Clergé'), ('Banni(e)', 'Bannis')], default='Groupe', max_length=100, null=True)),
                ('inscription_date', models.DateField()),
                ('completion_date', models.DateField()),
            ],
        ),
    ]
