# Generated by Django 4.1 on 2022-12-14 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pantheon',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='pantheon',
            name='created',
            field=models.DateField(auto_now=True),
        ),
    ]
