# Generated by Django 4.1 on 2022-12-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_alter_pantheon_options_pantheon_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='pantheon',
            name='fiche',
            field=models.CharField(default='https://marbrume.forumactif.com', max_length=1000),
        ),
    ]
