# Generated by Django 4.0.4 on 2022-07-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineevent',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
