# Generated by Django 4.0.4 on 2022-07-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_alter_timelineevent_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timelineevent',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
