# Generated by Django 4.0.4 on 2022-07-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_alter_timelineevent_options_timelineevent_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineevent',
            name='name',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
