# Generated by Django 4.0.4 on 2022-07-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0004_alter_timelineevent_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('text', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='timelineevent',
            options={'ordering': ['year', 'name']},
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='details',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='links',
            field=models.ManyToManyField(blank=True, to='timeline.timelinelinks'),
        ),
    ]
