# Generated by Django 4.0.4 on 2022-07-23 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0005_timelinelinks_alter_timelineevent_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimelineLinks',
            new_name='TimelineLink',
        ),
    ]
