# Generated by Django 4.0.4 on 2022-07-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0006_rename_timelinelinks_timelinelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineevent',
            name='consequences',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='details',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
