# Generated by Django 4.0.4 on 2022-07-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0007_timelineevent_consequences_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineevent',
            name='consequences',
            field=models.TextField(blank=True, max_length=30000, null=True),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='details',
            field=models.TextField(blank=True, max_length=30000, null=True),
        ),
    ]
