# Generated by Django 4.1.4 on 2023-03-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0008_alter_timelineevent_consequences_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timelineevent',
            options={'ordering': ['year', 'id']},
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='name',
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='origin',
            field=models.BooleanField(default=False),
        ),
    ]
