# Generated by Django 4.1.4 on 2023-03-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0009_alter_timelineevent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineevent',
            name='origin',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
