# Generated by Django 4.0.3 on 2022-03-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carriere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('rank', models.IntegerField(blank=True, choices=[('Rang', 'Rang'), (1, 1), (2, 2), (3, 3), (4, 4)], default=1, null=True)),
                ('For1', models.IntegerField(blank=True, null=True)),
                ('For1V', models.IntegerField(blank=True, default=0, null=True)),
                ('End1', models.IntegerField(blank=True, null=True)),
                ('End1V', models.IntegerField(blank=True, default=0, null=True)),
                ('Hab1', models.IntegerField(blank=True, null=True)),
                ('Hab1V', models.IntegerField(blank=True, default=0, null=True)),
                ('Char1', models.IntegerField(blank=True, null=True)),
                ('Char1V', models.IntegerField(blank=True, default=0, null=True)),
                ('Int1', models.IntegerField(blank=True, null=True)),
                ('Int1V', models.IntegerField(blank=True, default=0, null=True)),
                ('Ini1', models.IntegerField(blank=True, null=True)),
                ('Ini1V', models.IntegerField(blank=True, default=0, null=True)),
                ('Att1', models.IntegerField(blank=True, null=True)),
                ('Att1V', models.IntegerField(blank=True, default=0, null=True)),
                ('Par1', models.IntegerField(blank=True, null=True)),
                ('Par1V', models.IntegerField(blank=True, default=0, null=True)),
                ('Tir1', models.IntegerField(blank=True, null=True)),
                ('Tir1V', models.IntegerField(blank=True, default=0, null=True)),
                ('Na1', models.IntegerField(blank=True, null=True)),
                ('Na1V', models.IntegerField(blank=True, default=0, null=True)),
                ('Pv1', models.IntegerField(blank=True, null=True)),
                ('Pv1V', models.IntegerField(blank=True, default=0, null=True)),
                ('For2', models.IntegerField(blank=True, null=True)),
                ('End2', models.IntegerField(blank=True, null=True)),
                ('Hab2', models.IntegerField(blank=True, null=True)),
                ('Char2', models.IntegerField(blank=True, null=True)),
                ('Int2', models.IntegerField(blank=True, null=True)),
                ('Ini2', models.IntegerField(blank=True, null=True)),
                ('Att2', models.IntegerField(blank=True, null=True)),
                ('Par2', models.IntegerField(blank=True, null=True)),
                ('Tir2', models.IntegerField(blank=True, null=True)),
                ('Na2', models.IntegerField(blank=True, null=True)),
                ('Pv2', models.IntegerField(blank=True, null=True)),
                ('For3', models.IntegerField(blank=True, null=True)),
                ('End3', models.IntegerField(blank=True, null=True)),
                ('Hab3', models.IntegerField(blank=True, null=True)),
                ('Char3', models.IntegerField(blank=True, null=True)),
                ('Int3', models.IntegerField(blank=True, null=True)),
                ('Ini3', models.IntegerField(blank=True, null=True)),
                ('Att3', models.IntegerField(blank=True, null=True)),
                ('Par3', models.IntegerField(blank=True, null=True)),
                ('Tir3', models.IntegerField(blank=True, null=True)),
                ('Na3', models.IntegerField(blank=True, null=True)),
                ('Pv3', models.IntegerField(blank=True, null=True)),
                ('For4', models.IntegerField(blank=True, null=True)),
                ('End4', models.IntegerField(blank=True, null=True)),
                ('Hab4', models.IntegerField(blank=True, null=True)),
                ('Char4', models.IntegerField(blank=True, null=True)),
                ('Int4', models.IntegerField(blank=True, null=True)),
                ('Ini4', models.IntegerField(blank=True, null=True)),
                ('Att4', models.IntegerField(blank=True, null=True)),
                ('Par4', models.IntegerField(blank=True, null=True)),
                ('Tir4', models.IntegerField(blank=True, null=True)),
                ('Na4', models.IntegerField(blank=True, null=True)),
                ('Pv4', models.IntegerField(blank=True, null=True)),
                ('created', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
