# Generated by Django 4.0.3 on 2022-03-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrieres', '0002_carriere_for2v'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carriere',
            name='Att1V',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carriere',
            name='Char1V',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carriere',
            name='End1V',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carriere',
            name='For1V',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carriere',
            name='For2V',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carriere',
            name='Hab1V',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carriere',
            name='Ini1V',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carriere',
            name='Int1V',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carriere',
            name='Na1V',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carriere',
            name='Par1V',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carriere',
            name='Pv1V',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carriere',
            name='Tir1V',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
