# Generated by Django 4.0.3 on 2022-04-23 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrieres', '0005_remove_carriere_att1v_remove_carriere_att2v_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carriere',
            options={'ordering': ['name']},
        ),
    ]
