# Generated by Django 4.0.3 on 2022-05-26 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrieres', '0006_alter_carriere_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carriere',
            options={'ordering': ['group', 'name']},
        ),
        migrations.AddField(
            model_name='carriere',
            name='group',
            field=models.CharField(blank=True, choices=[('Groupe', 'Groupe'), ('Milice(ne)', 'Milice'), ('Habitant(e)', 'Peuple'), ('Noble', 'Noblesse'), ('Prêtre(sse)', 'Clergé'), ('Banni(e)', 'Bannis')], default='Groupe', max_length=50, null=True),
        ),
    ]
