# Generated by Django 4.0.3 on 2022-04-29 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competences', '0002_alter_skill_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='owner',
        ),
    ]
