# Generated by Django 4.0.3 on 2022-04-29 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competences', '0003_remove_skill_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='level',
        ),
    ]
