# Generated by Django 4.0.3 on 2022-04-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competences', '0004_remove_skill_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
