# Generated by Django 4.0.3 on 2022-04-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competences', '0006_skill_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='hasLevel',
            field=models.BooleanField(default=True),
        ),
    ]
