# Generated by Django 4.0.3 on 2022-04-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competences', '0007_skill_haslevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='hasLevel',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Oui', max_length=50),
        ),
    ]
