# Generated by Django 4.0.3 on 2022-04-30 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0006_alter_charactersheet_skills'),
        ('competences', '0009_skillsheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillsheet',
            name='skills',
        ),
        migrations.AddField(
            model_name='skillsheet',
            name='i',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='skillsheet',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fiches.charactersheet'),
        ),
    ]
