# Generated by Django 4.0.3 on 2022-04-30 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0008_charactersheet_skills'),
        ('competences', '0011_remove_skill_level_remove_skillsheet_i_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skillsheet',
            unique_together={('owner', 'skill')},
        ),
    ]
