# Generated by Django 4.0.3 on 2022-04-30 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competences', '0013_alter_skillsheet_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillsheet',
            options={'ordering': ['owner']},
        ),
        migrations.AlterUniqueTogether(
            name='skillsheet',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='skillsheet',
            name='owned',
        ),
    ]
