# Generated by Django 4.0.3 on 2022-05-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competences', '0014_alter_skillsheet_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillsheet',
            options={'ordering': ['skill']},
        ),
        migrations.AlterField(
            model_name='skill',
            name='hasLevel',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Oui', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='text',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
