# Generated by Django 4.0.3 on 2022-05-01 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0008_charactersheet_skills'),
        ('competences', '0015_alter_skillsheet_options_alter_skill_haslevel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillsheet',
            name='owner',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='fiches.charactersheet'),
        ),
        migrations.AlterField(
            model_name='skillsheet',
            name='skill',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='competences.skill'),
        ),
    ]
