# Generated by Django 4.0.3 on 2022-05-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competences', '0019_alter_skillsheet_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillsheet',
            name='level',
            field=models.CharField(blank=True, choices=[('Unique', 'Unique'), ('Niveau 1', 'Niveau 1'), ('Niveau 2', 'Niveau 2'), ('Niveau 3', 'Niveau 3')], default='Niveau 1', max_length=50, null=True),
        ),
    ]
