# Generated by Django 4.0.3 on 2022-05-07 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competences', '0020_alter_skillsheet_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillsheet',
            options={'ordering': ['skill__hasLevel', 'skill']},
        ),
    ]
