# Generated by Django 4.1 on 2022-11-13 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0026_alter_charactersheet_is_active'),
        ('competences', '0022_alter_skillsheet_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skillsheet',
            unique_together={('owner', 'skill')},
        ),
    ]
