flavorText = {
    "globalStatus": {
        "exalted": {"title": "", "text": ""},
        "positive": {"title": "", "text": ""},
        "neutral": {"title": "", "text": ""},
        "negative": {"title": "", "text": ""},
        "wanted": {"title": "", "text": ""},
    },
    "kingStatus": {
        "exalted": {"title": "", "text": ""},
        "positive": {"title": "", "text": ""},
        "neutral": {"title": "", "text": ""},
        "negative": {"title": "", "text": ""},
        "wanted": {"title": "", "text": ""},
    },
    "peopleStatus": {
        "exalted": {"title": "", "text": ""},
        "positive": {"title": "", "text": ""},
        "neutral": {"title": "", "text": ""},
        "negative": {"title": "", "text": ""},
        "wanted": {"title": "", "text": ""},
    },
    "nobilityStatus": {
        "exalted": {"title": "", "text": ""},
        "positive": {"title": "", "text": ""},
        "neutral": {"title": "", "text": ""},
        "negative": {"title": "", "text": ""},
        "wanted": {"title": "", "text": ""},
    },
    "clergyStatus": {
        "exalted": {"title": "", "text": ""},
        "positive": {"title": "", "text": ""},
        "neutral": {"title": "", "text": ""},
        "negative": {"title": "", "text": ""},
        "wanted": {"title": "", "text": ""},
    },
    "militiaStatus": {
        "exalted": {"title": "", "text": ""},
        "positive": {"title": "", "text": ""},
        "neutral": {"title": "", "text": ""},
        "negative": {"title": "", "text": ""},
        "wanted": {"title": "", "text": ""},
    },
    "labretStatus": {
        "exalted": {"title": "", "text": ""},
        "positive": {"title": "", "text": ""},
        "neutral": {"title": "", "text": ""},
        "negative": {"title": "", "text": ""},
        "wanted": {"title": "", "text": ""},
    },
    "banishedStatus": {
        "exalted": {"title": "", "text": ""},
        "positive": {"title": "", "text": ""},
        "neutral": {"title": "", "text": ""},
        "negative": {"title": "", "text": ""},
        "wanted": {"title": "", "text": ""},
    },
    "mafiaStatus": {
        "exalted": {"title": "", "text": ""},
        "positive": {"title": "", "text": ""},
        "neutral": {"title": "", "text": ""},
        "negative": {"title": "", "text": ""},
        "wanted": {"title": "", "text": ""},
    }
}
