flavorText = {
    "globalStatus": {
        "exalted": {"title": "Le pilier du Royaume", "text": "Vous vous êtes à maintes fois illustré. Vous êtes acclamé, respecté et élevé au rang de véritable héros de la nation!"},
        "positive": {"title": "Le brave", "text": "Vous attirez généralement la sympathie de vos semblables. Votre charmant sourire vous ouvre quelques portes qu'il vous appartient de franchir ou non."},
        "neutral": {"title": "Perdu dans la masse", "text": "Vous êtes plutôt quelconque. Personne n'a réellement d'avis sur vous, peut-être pour le mieux. Vous vivez votre vie en parallèle de celle des autres sans que personne n'y prête vraiment attention."},
        "negative": {"title": "Le marginal", "text": "Vous avez échoué à faire forte impression. Vous n'êtes pas un parangon de vertu pour vos commensaux qui n'hésitent pas à vous traiter comme un paria. Vous n'êtes clairement pas apprécié et ça se voit!"},
        "wanted": {"title": "Persona non grata", "text": "Vous n'avez pas votre place dans le royaume de notre bon Roi. Fripouille de bas-étage ou presque-fangeux, vous devez vivre votre vie loin de la société pour éviter le gibet."},
        "banished": {"title": "À définir", "text": "À définir"},
    },
    "kingStatus": {
        "exalted": {"title": "Favori", "text": "À sa simple évocation, vôtre nom ouvre toutes les portes du château. Qui sait, peut-être même celle de la Reine…"},
        "positive": {"title": "Estimé", "text": "Vous êtes dans les petits papiers du conseil. Encore quelques flatteries, vous y êtes presque !"},
        "neutral": {"title": "Inconnu", "text": "Vous n'évoquez rien de particulier, ni en bien ni en mal. En somme, vous êtes l'une des pauvres âmes survivantes du Royaume."},
        "negative": {"title": "Dissident", "text": "Votre nom commence, hélas, à remonter un peu trop souvent aux oreilles de la Couronne. Et pas pour de bonnes raisons."},
        "wanted": {"title": "Ennemi Royal", "text": "À trop vouloir jouer avec le feu, vous avez gagné un aller simple au bûcher. Ne sentez-vous pas l'odeur de roussi?"},
        "banished": {"title": "À définir", "text": "À définir"},
    },
    "nobilityStatus": {
        "exalted": {"title": "Meilleur parti", "text": "Votre nom est sur toutes les lèvres. On se bouscule à votre porte pour faire partie de votre carnet d'adresses."},
        "positive": {"title": "Connaissance respectable", "text": "Vous avez tout pour plaire à l'élite Marbrumienne. Il ne vous reste que peu d'efforts à fournir pour briller à l'Esplanade."},
        "neutral": {"title": "Marbrumien", "text": "Vous êtes négligeable."},
        "negative": {"title": "Pécore", "text": "Quelle chance que l'on daigne s'adresser à vous! Soyez donc un peu reconnaissant."},
        "wanted": {"title": "Traîne misère", "text": "Votre puanteur vous précède certainement. Cela expliquerait au moins les mines de dégoût que vous provoquez…"},
        "banished": {"title": "À définir", "text": "À définir"},
    },
    "peopleStatus": {
        "exalted": {"title": "Figure emblématique", "text": "Vous êtes porté aux nues par les petites gens. Votre nom est conté par les bardes et saltimbanques de tout le royaume."},
        "positive": {"title": "Âme charitable", "text": "Vos actions font chaud au coeur, vous n'hésitez jamais à mettre la main à la pâte."},
        "neutral": {"title": "Indifférent", "text": "Chacun chez soi et les moutons sont bien gardés."},
        "negative": {"title": "Filou", "text": "Une mauvaise action ou deux (ou trois) n'a jamais tué personne, ou presque."},
        "wanted": {"title": "Scélérat", "text": "Canaille! Malandrin! Passez vite votre chemin et serrez les fesses, la potence vous guette."},
        "banished": {"title": "À définir", "text": "À définir"},
    },
    "clergyStatus": {
        "exalted": {"title": "Dévot", "text": "Vous êtes à la droite des Trois. Certains vous voueraient volontiers un culte."},
        "positive": {"title": "Pieux", "text": "Véritable grenouille bénitier, vous vous complaisez dans la petite mare ecclésiastique."},
        "neutral": {"title": "Fidèle", "text": "Le lundi vous allez à la prière, le mardi vous faites la diète… Bref, vous êtes un bon croyant - même si vous arrangez parfois la vérité."},
        "negative": {"title": "Impie", "text": "Quelques visites supplémentaires au temple ne vous feraient pas de mal. Il semblerait que votre âme ait quelques péchés à faire absoudre."},
        "wanted": {"title": "Etioliste", "text": "Comme tous les hérétiques, vous n'irez qu'à un seul endroit: au bûcher."},
        "banished": {"title": "À définir", "text": "À définir"},
    },
    "militiaStatus": {
        "exalted": {"title": "Soutien infaillible", "text": "Vous êtes un incontournable de la milice. Votre contribution est reconnue de tous."},
        "positive": {"title": "Loyal", "text": "Vous apportez une aide appréciable, et la milice vous en remercie."},
        "neutral": {"title": "Sans histoire", "text": "Pas d'grabuge! Circulez, y'a rien à voir et qu'ça continue!"},
        "negative": {"title": "Crapule", "text": "Vous connaissez le nombre de pierres dans la troisième geôle sud. Évitez d'en faire votre dernière demeure."},
        "wanted": {"title": "Homme à abattre", "text": "Votre portrait est placardé sur tous les murs du Royaume. Priez pour ne rencontrer aucun crieur public."},
        "banished": {"title": "À définir", "text": "À définir"},
    },
    "banishedStatus": {
        "exalted": {"title": "Partisan", "text": "Vous êtes acquis à la Cause, camarade! Et ce, avec ou sans marque"},
        "positive": {"title": "Collaborateur acceptable", "text": "Toujours prêt à donner un coup de main… pour peu que votre nom ne soit pas mentionné."},
        "neutral": {"title": "Neutre", "text": "Neutre… Ou pas. Ils n'ont peut-être juste pas eu le temps de vous côtoyer assez."},
        "negative": {"title": "Hostile", "text": "Qui êtes vous ?! Que voulez-vous ?! Vos yeux sentent un peu trop les problèmes."},
        "wanted": {"title": "Ennemi", "text": "Ne traînez pas trop longtemps dans les marais, un accident est vite arrivé."},
        "banished": {"title": "À définir", "text": "À définir"},
    },
    "labretStatus": {
        "exalted": {"title": "Héros", "text": "Vous avez sué sang et eau pour le village. Les habitants vous vouent une reconnaissance éternelle."},
        "positive": {"title": "Bienfaiteur", "text": "Petit à petit, l'oiseau fait son nid ; vous apportez chaque jour une pierre à l'édifice."},
        "neutral": {"title": "Badaud", "text": "Vous vous laissez porter par le vent. Vous ne devez de compte à personne et personne ne vous en doit."},
        "negative": {"title": "Suspect", "text": "Rasez les murs, on vous tient à l'œil…"},
        "wanted": {"title": "Indésirable", "text": "Halte là! Faites demi-tour. Vous… ne passerez… PAS!"},
        "banished": {"title": "À définir", "text": "À définir"},
    },
    "sombreboisStatus": {
        "exalted": {"title": "Héros", "text": "Vous avez sué sang et eau pour le village. Les habitants vous vouent une reconnaissance éternelle."},
        "positive": {"title": "Bienfaiteur", "text": "Petit à petit, l'oiseau fait son nid ; vous apportez chaque jour une pierre à l'édifice."},
        "neutral": {"title": "Badaud", "text": "Vous vous laissez porter par le vent. Vous ne devez de compte à personne et personne ne vous en doit."},
        "negative": {"title": "Suspect", "text": "Rasez les murs, on vous tient à l'œil…"},
        "wanted": {"title": "Indésirable", "text": "Halte là! Faites demi-tour. Vous… ne passerez… PAS!"},
        "banished": {"title": "À définir", "text": "À définir"},
    },
    "mafiaStatus": {
        "exalted": {"title": "Partisan", "text": "Vous êtes acquis à la Cause, camarade! Et ce, avec ou sans marque"},
        "positive": {"title": "Collaborateur acceptable", "text": "Toujours prêt à donner un coup de main… pour peu que votre nom ne soit pas mentionné."},
        "neutral": {"title": "Neutre", "text": "Neutre… Ou pas. Ils n'ont peut-être juste pas eu le temps de vous côtoyer assez."},
        "negative": {"title": "Hostile", "text": "Qui êtes vous ?! Que voulez-vous ?! Vos yeux sentent un peu trop les problèmes."},
        "wanted": {"title": "Ennemi", "text": "Ne traînez pas trop longtemps sur notre territoire, un accident est vite arrivé."},
        "banished": {"title": "À définir", "text": "À définir"},
    },
    "guildStatus": {
        "exalted": {"title": "Membre émérite", "text": "Sans vous, il n'y aurait pas de guilde. Enfin, presque. C'est tout comme."},
        "positive": {"title": "Elément moteur", "text": "Votre talent est reconnu et votre avis est souvent sollicité. Vous avez de la suite dans les idées."},
        "neutral": {"title": "Membre", "text": "Vous faites le travail et c'est déjà pas mal."},
        "negative": {"title": "Tire au flanc", "text": "Quand est-ce qu'on mange ? Il n'y a pas de jour de fête chômé à Marbrume ? Qui donc a osé vous réveiller de la sieste ?"},
        "wanted": {"title": "Raté", "text": "Vous êtes une catastrophe ambulante, visiblement vous vous êtes trompé de voie."},
        "banished": {"title": "À définir", "text": "À définir"},
    },
}
