achievementsList = [
        {'id': 1, 'title': 'succes_1',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 2, 'title': 'succes_2',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 3, 'title': 'succes_3',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 4, 'title': 'succes_4',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 5, 'title': 'succes_5',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 6, 'title': 'succes_6',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 7, 'title': 'succes_7',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 8, 'title': 'succes_8',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 9, 'title': 'succes_9',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 10, 'title': 'succes_10',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 11, 'title': 'succes_11',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 12, 'title': 'succes_12',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 13, 'title': 'succes_13',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 14, 'title': 'succes_14',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 15, 'title': 'succes_15',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 16, 'title': 'succes_16',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 17, 'title': 'succes_17',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 18, 'title': 'succes_18',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 19, 'title': 'succes_19',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 20, 'title': 'succes_20',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 21, 'title': 'succes_21',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 22, 'title': 'succes_22',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 23, 'title': 'succes_23',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 24, 'title': 'succes_24',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 25, 'title': 'succes_25',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 26, 'title': 'succes_26',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 27, 'title': 'succes_27',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 28, 'title': 'succes_28',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 29, 'title': 'succes_29',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 30, 'title': 'succes_30',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 31, 'title': 'succes_31',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 32, 'title': 'succes_32',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 33, 'title': 'succes_33',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 34, 'title': 'succes_34',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 35, 'title': 'succes_35',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 36, 'title': 'succes_36',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 37, 'title': 'succes_37',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 38, 'title': 'succes_38',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 39, 'title': 'succes_39',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 40, 'title': 'succes_40',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 41, 'title': 'succes_41',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 42, 'title': 'succes_42',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 43, 'title': 'succes_43',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 44, 'title': 'succes_44',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 45, 'title': 'succes_45',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 46, 'title': 'succes_46',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 47, 'title': 'succes_47',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 48, 'title': 'succes_48',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 49, 'title': 'succes_49',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 50, 'title': 'succes_50',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 51, 'title': 'succes_51',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 52, 'title': 'succes_52',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 53, 'title': 'succes_53',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 54, 'title': 'succes_54',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 55, 'title': 'succes_55',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 56, 'title': 'succes_56',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 57, 'title': 'succes_57',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 58, 'title': 'succes_58',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 59, 'title': 'succes_59',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 60, 'title': 'succes_60',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 61, 'title': 'succes_61',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 62, 'title': 'succes_62',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 63, 'title': 'succes_63',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 64, 'title': 'succes_64',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 65, 'title': 'succes_65',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 66, 'title': 'succes_66',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 67, 'title': 'succes_67',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 68, 'title': 'succes_68',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 69, 'title': 'succes_69',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 70, 'title': 'succes_70',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 71, 'title': 'succes_71',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 72, 'title': 'succes_72',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 73, 'title': 'succes_73',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 74, 'title': 'succes_74',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 75, 'title': 'succes_75',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 76, 'title': 'succes_76',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 77, 'title': 'succes_77',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 78, 'title': 'succes_78',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 79, 'title': 'succes_79',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 80, 'title': 'succes_80',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 81, 'title': 'succes_81',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 82, 'title': 'succes_82',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 83, 'title': 'succes_83',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 84, 'title': 'succes_84',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 85, 'title': 'succes_85',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 86, 'title': 'succes_86',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 87, 'title': 'succes_87',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 88, 'title': 'succes_88',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 89, 'title': 'succes_89',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'},
        {'id': 90, 'title': 'succes_90',
            'text': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit'}
    ]