finishers = [
    {"name": "Denea Alberick", "group": "Habitant(e)", "inscription_date": "21/09/2015", "completion_date": "01/03/2017",
     "fiche": "https://marbrume.forumactif.com/t93-denea-alberick-terminer"},
    {"name": "Grâce de Brasey", "group": "Noble", "inscription_date": "25/10/2015",
        "completion_date": "01/03/2017", "fiche": "https://marbrume.forumactif.com/t202-grace-de-brasey-terminer"},
    {"name": "Hérald Dreit", "group": "Milice(ne)", "inscription_date": "27/10/2016", "completion_date": "12/03/2017",
     "fiche": "https://marbrume.forumactif.com/t1589-herald-dreit-le-sens-du-devoir"},
    {"name": "Victor de Rougelac", "group": "Noble", "inscription_date": "23/09/2015", "completion_date": "04/04/2017",
        "fiche": "https://marbrume.forumactif.com/t98-victor-de-rougelac-fiche-validee"},
    {"name": "Sydonnie d'Algrange", "group": "Milice(ne)", "inscription_date": "20/07/2016", "completion_date": "10/04/2017",
     "fiche": "https://marbrume.forumactif.com/t1357-sydonnie-d-algrange-fiche-terminee"},
    {"name": "Theodren Hilaire", "group": "Habitant(e)", "inscription_date": "26/03/2017", "completion_date": "20/06/2017",
     "fiche": "https://marbrume.forumactif.com/t2089-theodren-hilaire-fiche-terminee"},
    {"name": "Constance", "group": "Prêtre(sse)", "inscription_date": "28/03/2017", "completion_date": "25/07/2017",
     "fiche": "https://marbrume.forumactif.com/t2094-constance-simple-pretresse-termine"},
    {"name": "Séraphin Chantebrume", "group": "Milice(ne)", "inscription_date": "07/10/2016",
     "completion_date": "22/01/2019", "fiche": "https://marbrume.forumactif.com/t1537-seraphin-chantebrume"},
    {"name": "Alexandre de Terresang", "group": "Noble", "inscription_date": "18/12/2015", "completion_date": "03/03/2019",
        "fiche": "https://marbrume.forumactif.com/t510-alexandre-le-brule-de-terresang-terminee"},
    {"name": "Mathilde", "group": "Habitant(e)", "inscription_date": "07/01/2019", "completion_date": "10/07/2019",
     "fiche": "https://marbrume.forumactif.com/t3115-mathilde-dumas-celle-qui-soigne-ton-estomac-validee"},
    {"name": "Roland de Rivefière", "group": "Noble", "inscription_date": "24/01/2019",
        "completion_date": "10/07/2019", "fiche": "https://marbrume.forumactif.com/t3215-roland-de-rivefiere-valide"},
    {"name": "Aymeric de Beauharnais", "group": "Noble", "inscription_date": "24/03/2017",
        "completion_date": "09/08/2019", "fiche": "https://marbrume.forumactif.com/t2077-aymeric-de-beauharnais"},
    {"name": "Merrick Lorren", "group": "Milice(ne)", "inscription_date": "20/01/2019", "completion_date": "04/09/2019",
     "fiche": "https://marbrume.forumactif.com/t3198-merrick-lorren-valide"},
    {"name": "Isaure Hildegarde", "group": "Banni(e)", "inscription_date": "30/11/2018", "completion_date": "06/09/2019",
     "fiche": "https://marbrume.forumactif.com/t2951-isaure-hildegarde-terminee"},
    {"name": "Elisabeth Blanchevigne", "group": "Milice(ne)", "inscription_date": "07/05/2019", "completion_date": "10/01/2020",
     "fiche": "https://marbrume.forumactif.com/t3822-elisabeth-blanchevigne-validee"},
    {"name": "Lothaire Ferbois", "group": "Habitant(e)", "inscription_date": "24/01/2017", "completion_date": "24/02/2020",
     "fiche": "https://marbrume.forumactif.com/t1761-lothaire-ferbois-termine"},
    {"name": "Aaron Clay", "group": "Prêtre(sse)", "inscription_date": "09/11/2018", "completion_date": "06/04/2020",
     "fiche": "https://marbrume.forumactif.com/t2875-aaron-clay-validee"},
    {"name": "Clovis Legrand", "group": "Milice(ne)", "inscription_date": "06/05/2017", "completion_date": "17/04/2020",
     "fiche": "https://marbrume.forumactif.com/t2280-clovis-legrand-le-forgeron-devenu-milicien"},
    {"name": "Jocelyn", "group": "Banni(e)", "inscription_date": "02/12/2018", "completion_date": "18/04/2020",
     "fiche": "https://marbrume.forumactif.com/t2963-jocelyn-le-fauconnier-banni-fiche-validee"},
    {"name": "Darius Vortigern", "group": "Habitant(e)", "inscription_date": "22/11/2019", "completion_date": "03/07/2020",
     "fiche": "https://marbrume.forumactif.com/t4494-darius-vortigern-validee"},
    {"name": "Jacob de Rivefière", "group": "Noble", "inscription_date": "15/04/2020", "completion_date": "08/07/2020",
        "fiche": "https://marbrume.forumactif.com/t4937-jacob-de-rivefiere-fiche-validee"},
    {"name": "Ombeline", "group": "Habitant(e)", "inscription_date": "27/10/2018", "completion_date": "09/10/2020",
     "fiche": "https://marbrume.forumactif.com/t2814-ombeline-validee"},
    {"name": "Estelle Lorren", "group": "Habitant(e)", "inscription_date": "17/10/2018", "completion_date": "09/10/2020",
     "fiche": "https://marbrume.forumactif.com/t2778-estelle-de-chantauvent-validee"},
    {"name": "Desmond de Rochemont", "group": "Noble", "inscription_date": "19/09/2020", "completion_date": "20/12/2020",
        "fiche": "https://marbrume.forumactif.com/t5329-desmond-de-rochemont-fiche-validee"},
    {"name": "Alban Laforge", "group": "Habitant(e)", "inscription_date": "22/02/2021", "completion_date": "09/05/2021",
     "fiche": "https://marbrume.forumactif.com/t5621-alban-laforge-validee"},
    {"name": "Aeryn Monclar", "group": "Habitant(e)", "inscription_date": "14/02/2019", "completion_date": "13/06/2021",
     "fiche": "https://marbrume.forumactif.com/t3354-aeryn-monclar-validee"},
    {"name": "Morgred Pêcheur", "group": "Habitant(e)", "inscription_date": "08/08/2021", "completion_date": "11/01/2022",
     "fiche": "https://marbrume.forumactif.com/t6068-morgred-pecheur-validee"},
    {"name": "Esmée de Sabran", "group": "Noble", "inscription_date": "17/11/2021",
        "completion_date": "17/01/2022", "fiche": "https://marbrume.forumactif.com/t6199-esmee-de-sabranvalidee"},
    {"name": "Gudrun Mercier", "group": "Prêtre(sse)", "inscription_date": "30/05/2021", "completion_date": "06/04/2022",
     "fiche": "https://marbrume.forumactif.com/t5850-gudrun-mercier-validee"},
]

customs = [
    {"name": "Victor de Rougelac", "group": "Noble", "inscription_date": "23/09/2015", "completion_date": "04/01/2020",
        "fiche": "https://marbrume.forumactif.com/t98-victor-de-rougelac-fiche-validee"},
    {"name": "Desmond de Rochemont", "group": "Noble", "inscription_date": "19/09/2020", "completion_date": "10/03/2022",
        "fiche": "https://marbrume.forumactif.com/t5329-desmond-de-rochemont-fiche-validee"},
]