# Generated by Django 4.0.3 on 2022-05-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, choices=[('Type', 'Type'), ('Armure légère', 'Armure légère'), ('Armure moyenne', 'Armure moyenne'), ('Armure lourde', 'Armure lourde')], default='Type', max_length=50, null=True)),
                ('text', models.TextField(blank=True, max_length=2000, null=True)),
                ('areas', models.CharField(blank=True, choices=[('Zone', 'Zone'), ('Tête', 'Tête'), ('Mains', 'Mains'), ('Torse', 'Torse'), ('Jambes', 'Jambes')], default='Zone', max_length=50, null=True)),
                ('protection', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
