# Generated by Django 4.0.3 on 2022-05-08 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0008_charactersheet_skills'),
        ('equipement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, choices=[('Type', 'Type'), ('Arme à une main', 'Arme à une main'), ('Arme à deux mains', 'Arme à deux mains'), ('Arme de tir', 'Arme de tir'), ('Arme de jet', 'Arme de jet'), ('Bouclier', 'Bouclier')], default='Type', max_length=50, null=True)),
                ('text', models.TextField(blank=True, max_length=2000, null=True)),
                ('damages', models.IntegerField(blank=True, null=True)),
                ('parry', models.IntegerField(blank=True, null=True)),
                ('penalty', models.TextField(blank=True, max_length=200, null=True)),
                ('note', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Stuff',
            new_name='Armor',
        ),
        migrations.CreateModel(
            name='StuffSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armor', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipement.armor')),
                ('owner', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='fiches.charactersheet')),
                ('weapon', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipement.weapon')),
            ],
            options={
                'ordering': ['armor', 'weapon'],
            },
        ),
    ]
