# Generated by Django 4.0.3 on 2022-05-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0002_weapon_rename_stuff_armor_stuffsheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='damages',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='penalty',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
