# Generated by Django 4.0.3 on 2022-05-15 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0004_alter_weapon_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='armor',
            options={'ordering': ['type', 'name']},
        ),
    ]
