# Generated by Django 4.0.3 on 2022-05-19 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0005_alter_armor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stuffsheet',
            options={'ordering': ['weapon', 'armor']},
        ),
    ]
