# Generated by Django 4.0.3 on 2022-08-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0007_armoryweaponsnotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='armoryweaponsnotes',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
