# Generated by Django 4.1 on 2022-11-13 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0027_charactersheet_skill_set'),
        ('equipement', '0011_alter_armoryweaponsnote_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stuffsheet',
            unique_together={('owner', 'armor', 'weapon')},
        ),
    ]
