# Generated by Django 4.1.4 on 2023-01-01 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0029_charactersheet_fiche'),
        ('equipement', '0012_alter_stuffsheet_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('owner', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='fiches.charactersheet')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
