# Generated by Django 4.0.3 on 2022-03-15 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carrieres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('group', models.CharField(choices=[('Groupe', 'Groupe'), ('Milice(ne)', 'Milice'), ('Habitant(e)', 'Peuple'), ('Noble', 'Noblesse'), ('Prêtre(sse)', 'Clergé'), ('Banni(e)', 'Bannis')], default='Groupe', max_length=50, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('For', models.IntegerField(blank=True, default=8, null=True)),
                ('End', models.IntegerField(blank=True, default=8, null=True)),
                ('Hab', models.IntegerField(blank=True, default=8, null=True)),
                ('Char', models.IntegerField(blank=True, default=8, null=True)),
                ('Int', models.IntegerField(blank=True, default=8, null=True)),
                ('Ini', models.IntegerField(blank=True, default=8, null=True)),
                ('Att', models.IntegerField(blank=True, default=8, null=True)),
                ('Par', models.IntegerField(blank=True, default=8, null=True)),
                ('Tir', models.IntegerField(blank=True, default=8, null=True)),
                ('Na', models.IntegerField(blank=True, default=1, null=True)),
                ('Pv', models.IntegerField(blank=True, default=60, null=True)),
                ('created', models.TimeField(auto_now_add=True, null=True)),
                ('path', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carrieres.carriere')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
