# Generated by Django 4.0.3 on 2022-03-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('group', models.CharField(choices=[('Milice', 'Milicien'), ('Peuple', 'Peuple'), ('Noblesse', 'Noble'), ('Clergé', 'Prêtre(sse)'), ('Banni', 'Banni')], max_length=50)),
                ('rank', models.IntegerField()),
                ('path', models.CharField(max_length=50)),
                ('For', models.IntegerField(default=8)),
                ('End', models.IntegerField(default=8)),
                ('Hab', models.IntegerField(default=8)),
                ('Char', models.IntegerField(default=8)),
                ('Int', models.IntegerField(default=8)),
                ('Ini', models.IntegerField(default=8)),
                ('Att', models.IntegerField(default=8)),
                ('Par', models.IntegerField(default=8)),
                ('Tir', models.IntegerField(default=8)),
                ('Na', models.IntegerField(default=2)),
                ('Pv', models.IntegerField(default=60)),
            ],
        ),
    ]
