# Generated by Django 4.0.3 on 2022-04-23 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carrieres', '0006_alter_carriere_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('group', models.CharField(blank=True, choices=[('Groupe', 'Groupe'), ('Milice(ne)', 'Milice'), ('Habitant(e)', 'Peuple'), ('Noble', 'Noblesse'), ('Prêtre(sse)', 'Clergé'), ('Banni(e)', 'Bannis')], default='Groupe', max_length=50, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('For', models.IntegerField(blank=True, default=8, null=True)),
                ('End', models.IntegerField(blank=True, default=8, null=True)),
                ('Hab', models.IntegerField(blank=True, default=8, null=True)),
                ('Char', models.IntegerField(blank=True, default=8, null=True)),
                ('Int', models.IntegerField(blank=True, default=8, null=True)),
                ('Ini', models.IntegerField(blank=True, default=8, null=True)),
                ('Att', models.IntegerField(blank=True, default=8, null=True)),
                ('Par', models.IntegerField(blank=True, default=8, null=True)),
                ('Tir', models.IntegerField(blank=True, default=8, null=True)),
                ('Na', models.IntegerField(blank=True, default=1, null=True)),
                ('Pv', models.IntegerField(blank=True, default=60, null=True)),
                ('member', models.BooleanField(default=False)),
                ('For1V', models.IntegerField(blank=True, default=0, null=True)),
                ('End1V', models.IntegerField(blank=True, default=0, null=True)),
                ('Hab1V', models.IntegerField(blank=True, default=0, null=True)),
                ('Char1V', models.IntegerField(blank=True, default=0, null=True)),
                ('Int1V', models.IntegerField(blank=True, default=0, null=True)),
                ('Ini1V', models.IntegerField(blank=True, default=0, null=True)),
                ('Att1V', models.IntegerField(blank=True, default=0, null=True)),
                ('Par1V', models.IntegerField(blank=True, default=0, null=True)),
                ('Tir1V', models.IntegerField(blank=True, default=0, null=True)),
                ('Na1V', models.IntegerField(blank=True, default=0, null=True)),
                ('Pv1V', models.IntegerField(blank=True, default=0, null=True)),
                ('For2V', models.IntegerField(blank=True, default=0, null=True)),
                ('End2V', models.IntegerField(blank=True, default=0, null=True)),
                ('Hab2V', models.IntegerField(blank=True, default=0, null=True)),
                ('Char2V', models.IntegerField(blank=True, default=0, null=True)),
                ('Int2V', models.IntegerField(blank=True, default=0, null=True)),
                ('Ini2V', models.IntegerField(blank=True, default=0, null=True)),
                ('Att2V', models.IntegerField(blank=True, default=0, null=True)),
                ('Par2V', models.IntegerField(blank=True, default=0, null=True)),
                ('Tir2V', models.IntegerField(blank=True, default=0, null=True)),
                ('Na2V', models.IntegerField(blank=True, default=0, null=True)),
                ('Pv2V', models.IntegerField(blank=True, default=0, null=True)),
                ('For3V', models.IntegerField(blank=True, default=0, null=True)),
                ('End3V', models.IntegerField(blank=True, default=0, null=True)),
                ('Hab3V', models.IntegerField(blank=True, default=0, null=True)),
                ('Char3V', models.IntegerField(blank=True, default=0, null=True)),
                ('Int3V', models.IntegerField(blank=True, default=0, null=True)),
                ('Ini3V', models.IntegerField(blank=True, default=0, null=True)),
                ('Att3V', models.IntegerField(blank=True, default=0, null=True)),
                ('Par3V', models.IntegerField(blank=True, default=0, null=True)),
                ('Tir3V', models.IntegerField(blank=True, default=0, null=True)),
                ('Na3V', models.IntegerField(blank=True, default=0, null=True)),
                ('Pv3V', models.IntegerField(blank=True, default=0, null=True)),
                ('For4V', models.IntegerField(blank=True, default=0, null=True)),
                ('End4V', models.IntegerField(blank=True, default=0, null=True)),
                ('Hab4V', models.IntegerField(blank=True, default=0, null=True)),
                ('Char4V', models.IntegerField(blank=True, default=0, null=True)),
                ('Int4V', models.IntegerField(blank=True, default=0, null=True)),
                ('Ini4V', models.IntegerField(blank=True, default=0, null=True)),
                ('Att4V', models.IntegerField(blank=True, default=0, null=True)),
                ('Par4V', models.IntegerField(blank=True, default=0, null=True)),
                ('Tir4V', models.IntegerField(blank=True, default=0, null=True)),
                ('Na4V', models.IntegerField(blank=True, default=0, null=True)),
                ('Pv4V', models.IntegerField(blank=True, default=0, null=True)),
                ('created', models.TimeField(auto_now_add=True, null=True)),
                ('path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carrieres.carriere')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
