# Generated by Django 4.0.3 on 2022-04-23 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charactersheet',
            name='member',
        ),
    ]
