# Generated by Django 4.0.3 on 2022-03-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charactersheet',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='charactersheet',
            name='created',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
