# Generated by Django 4.0.3 on 2022-03-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0002_charactersheet_att1v_charactersheet_char1v_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactersheet',
            name='Att1V',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='Char1V',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='End1V',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='For1V',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='Hab1V',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='Ini1V',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='Int1V',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='Na1V',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='Par1V',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='Pv1V',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='Tir1V',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
