# Generated by Django 4.0.3 on 2022-04-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0002_remove_charactersheet_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactersheet',
            name='member',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
    ]
