# Generated by Django 4.0.3 on 2022-03-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0003_alter_charactersheet_group_alter_charactersheet_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactersheet',
            name='path',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
