# Generated by Django 4.0.3 on 2022-04-23 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0003_charactersheet_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactersheet',
            name='member',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50),
        ),
    ]
