# Generated by Django 4.0.3 on 2022-03-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0004_charactersheet_att2v_charactersheet_att3v_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactersheet',
            name='group',
            field=models.CharField(blank=True, choices=[('Groupe', 'Groupe'), ('Milice(ne)', 'Milice'), ('Habitant(e)', 'Peuple'), ('Noble', 'Noblesse'), ('Prêtre(sse)', 'Clergé'), ('Banni(e)', 'Bannis')], default='Groupe', max_length=50, null=True),
        ),
    ]
