# Generated by Django 4.0.3 on 2022-03-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0004_alter_charactersheet_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactersheet',
            name='Att',
            field=models.IntegerField(blank=True, default=8, null=True),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='Char',
            field=models.IntegerField(blank=True, default=8, null=True),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='End',
            field=models.IntegerField(blank=True, default=8, null=True),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='For',
            field=models.IntegerField(blank=True, default=8, null=True),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='Hab',
            field=models.IntegerField(blank=True, default=8, null=True),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='Ini',
            field=models.IntegerField(blank=True, default=8, null=True),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='Int',
            field=models.IntegerField(blank=True, default=8, null=True),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='Na',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='Par',
            field=models.IntegerField(blank=True, default=8, null=True),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='Pv',
            field=models.IntegerField(blank=True, default=60, null=True),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='Tir',
            field=models.IntegerField(blank=True, default=8, null=True),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
