# Generated by Django 4.0.3 on 2022-03-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0005_alter_charactersheet_att_alter_charactersheet_char_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactersheet',
            name='group',
            field=models.CharField(blank=True, choices=[('Groupe', 'Groupe'), ('Milice', 'Milicien'), ('Peuple', 'Peuple'), ('Noblesse', 'Noble'), ('Clergé', 'Prêtre(sse)'), ('Banni', 'Banni')], default='Groupe', max_length=50, null=True),
        ),
    ]
