# Generated by Django 4.0.3 on 2022-04-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competences', '0009_skillsheet'),
        ('fiches', '0005_charactersheet_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactersheet',
            name='skills',
            field=models.ManyToManyField(blank=True, to='competences.skill'),
        ),
    ]
