# Generated by Django 4.0.3 on 2022-04-30 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0006_alter_charactersheet_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charactersheet',
            name='skills',
        ),
    ]
