# Generated by Django 4.0.3 on 2022-04-11 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0006_alter_charactersheet_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charactersheet',
            options={'ordering': ['-id']},
        ),
    ]
