# Generated by Django 4.0.1 on 2022-03-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0007_alter_charactersheet_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactersheet',
            name='Na',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='group',
            field=models.CharField(choices=[('Groupe', 'Groupe'), ('Milice', 'Milicien(ne)'), ('Peuple', 'Habitant(e)'), ('Noblesse', 'Noble'), ('Clergé', 'Prêtre(sse)'), ('Banni', 'Banni(e)')], default='Groupe', max_length=50, null=True),
        ),
    ]
