# Generated by Django 4.0.1 on 2022-03-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0008_alter_charactersheet_na_alter_charactersheet_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactersheet',
            name='group',
            field=models.CharField(choices=[('Groupe', 'Groupe'), ('Milice(ne)', 'Milice'), ('Habitant(e)', 'Peuple'), ('Noble', 'Noblesse'), ('Prêtre(sse)', 'Clergé'), ('Banni(e)', 'Bannis')], default='Groupe', max_length=50, null=True),
        ),
    ]
