# Generated by Django 4.0.3 on 2022-05-13 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0008_charactersheet_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactersheet',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
