# Generated by Django 4.0.3 on 2022-05-13 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0009_charactersheet_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charactersheet',
            name='created',
        ),
    ]
