# Generated by Django 4.0.3 on 2022-05-13 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0010_remove_charactersheet_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charactersheet',
            old_name='date',
            new_name='created',
        ),
    ]
