# Generated by Django 4.0.3 on 2022-05-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0011_rename_date_charactersheet_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactersheet',
            name='is_active',
            field=models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Oui', max_length=50),
        ),
        migrations.AddField(
            model_name='charactersheet',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
