# Generated by Django 4.0.3 on 2022-05-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competences', '0021_alter_skillsheet_options'),
        ('fiches', '0012_charactersheet_is_active_charactersheet_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactersheet',
            name='gender',
            field=models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], default='Homme', max_length=50),
        ),
        migrations.AddField(
            model_name='charactersheet',
            name='has_aliases',
            field=models.ManyToManyField(blank=True, editable=False, to='fiches.charactersheet'),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='skills',
            field=models.ManyToManyField(blank=True, editable=False, through='competences.SkillSheet', to='competences.skill'),
        ),
    ]
