# Generated by Django 4.0.3 on 2022-05-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0013_charactersheet_gender_charactersheet_has_aliases_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactersheet',
            name='has_aliases',
            field=models.ManyToManyField(blank=True, to='fiches.charactersheet'),
        ),
    ]
