# Generated by Django 4.0.3 on 2022-05-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0014_alter_charactersheet_has_aliases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactersheet',
            name='has_aliases',
            field=models.ManyToManyField(to='fiches.charactersheet'),
        ),
    ]
