# Generated by Django 4.0.3 on 2022-05-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0015_alter_charactersheet_has_aliases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactersheet',
            name='gender',
            field=models.CharField(blank=True, choices=[('Homme', 'Homme'), ('Femme', 'Femme')], default='Homme', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='has_aliases',
            field=models.ManyToManyField(blank=True, to='fiches.charactersheet'),
        ),
    ]
