# Generated by Django 4.0.3 on 2022-05-15 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0017_alter_charactersheet_has_aliases'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aliase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='charactersheet',
            name='has_aliases',
            field=models.ManyToManyField(blank=True, to='fiches.charactersheet'),
        ),
        migrations.CreateModel(
            name='AliasesSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('aliases', models.ManyToManyField(blank=True, to='fiches.aliase')),
                ('owner', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to='fiches.charactersheet')),
            ],
        ),
        migrations.AddField(
            model_name='aliase',
            name='name',
            field=models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to='fiches.charactersheet'),
        ),
    ]
