# Generated by Django 4.0.3 on 2022-05-20 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0021_alter_charactersheet_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactersheet',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
    ]
