# Generated by Django 4.0.4 on 2022-07-23 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0024_alter_charactersheet_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aliase',
            options={'ordering': ['owner__name']},
        ),
        migrations.AlterModelOptions(
            name='aliasessheet',
            options={'ordering': ['owner__name']},
        ),
        migrations.AlterModelOptions(
            name='charactersheet',
            options={'ordering': ['-created']},
        ),
    ]
