# Generated by Django 4.1 on 2022-10-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0025_alter_aliase_options_alter_aliasessheet_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactersheet',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
