# Generated by Django 4.1 on 2022-11-13 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0027_charactersheet_skill_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charactersheet',
            name='skill_set',
        ),
    ]
