# Generated by Django 4.1 on 2022-12-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0028_remove_charactersheet_skill_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactersheet',
            name='fiche',
            field=models.CharField(blank=True, default='https://marbrume.forumactif.com/f8-fiches-de-personnages', max_length=255, null=True),
        ),
    ]
