# Generated by Django 4.0.3 on 2022-04-11 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fiches', '0007_alter_charactersheet_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReputationBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fiches.charactersheet')),
            ],
        ),
    ]
