# Generated by Django 4.0.3 on 2022-04-18 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fiches', '0007_alter_charactersheet_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleReputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('globalStatus', models.CharField(choices=[('Excellente', 'Excellente'), ('Positive', 'Positive'), ('Neutre', 'Neutre'), ('Négative', 'Négative'), ('Recherché', 'Recherché')], default='Neutre', max_length=50)),
                ('kingStatus', models.CharField(choices=[('Excellente', 'Excellente'), ('Positive', 'Positive'), ('Neutre', 'Neutre'), ('Négative', 'Négative'), ('Recherché', 'Recherché')], default='Neutre', max_length=50)),
                ('nobilityStatus', models.CharField(choices=[('Excellente', 'Excellente'), ('Positive', 'Positive'), ('Neutre', 'Neutre'), ('Négative', 'Négative'), ('Recherché', 'Recherché')], default='Neutre', max_length=50)),
                ('peopleStatus', models.CharField(choices=[('Excellente', 'Excellente'), ('Positive', 'Positive'), ('Neutre', 'Neutre'), ('Négative', 'Négative'), ('Recherché', 'Recherché')], default='Neutre', max_length=50)),
                ('clergyStatus', models.CharField(choices=[('Excellente', 'Excellente'), ('Positive', 'Positive'), ('Neutre', 'Neutre'), ('Négative', 'Négative'), ('Recherché', 'Recherché')], default='Neutre', max_length=50)),
                ('labretStatus', models.CharField(choices=[('Excellente', 'Excellente'), ('Positive', 'Positive'), ('Neutre', 'Neutre'), ('Négative', 'Négative'), ('Recherché', 'Recherché')], default='Neutre', max_length=50)),
                ('owner', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='fiches.charactersheet')),
            ],
        ),
        migrations.CreateModel(
            name='NobilityReputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('globalStatus', models.CharField(choices=[('Excellente', 'Excellente'), ('Positive', 'Positive'), ('Neutre', 'Neutre'), ('Négative', 'Négative'), ('Recherché', 'Recherché')], default='Neutre', max_length=50)),
                ('kingStatus', models.CharField(choices=[('Excellente', 'Excellente'), ('Positive', 'Positive'), ('Neutre', 'Neutre'), ('Négative', 'Négative'), ('Recherché', 'Recherché')], default='Neutre', max_length=50)),
                ('nobilityStatus', models.CharField(choices=[('Excellente', 'Excellente'), ('Positive', 'Positive'), ('Neutre', 'Neutre'), ('Négative', 'Négative'), ('Recherché', 'Recherché')], default='Positive', max_length=50)),
                ('peopleStatus', models.CharField(choices=[('Excellente', 'Excellente'), ('Positive', 'Positive'), ('Neutre', 'Neutre'), ('Négative', 'Négative'), ('Recherché', 'Recherché')], default='Neutre', max_length=50)),
                ('clergyStatus', models.CharField(choices=[('Excellente', 'Excellente'), ('Positive', 'Positive'), ('Neutre', 'Neutre'), ('Négative', 'Négative'), ('Recherché', 'Recherché')], default='Neutre', max_length=50)),
                ('labretStatus', models.CharField(choices=[('Excellente', 'Excellente'), ('Positive', 'Positive'), ('Neutre', 'Neutre'), ('Négative', 'Négative'), ('Recherché', 'Recherché')], default='Neutre', max_length=50)),
                ('owner', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='fiches.charactersheet')),
            ],
        ),
        migrations.CreateModel(
            name='MilitiaReputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('globalStatus', models.CharField(choices=[('Excellente', 'Excellente'), ('Positive', 'Positive'), ('Neutre', 'Neutre'), ('Négative', 'Négative'), ('Recherché', 'Recherché')], default='Positive', max_length=50)),
                ('kingStatus', models.CharField(choices=[('Excellente', 'Excellente'), ('Positive', 'Positive'), ('Neutre', 'Neutre'), ('Négative', 'Négative'), ('Recherché', 'Recherché')], default='Neutre', max_length=50)),
                ('nobilityStatus', models.CharField(choices=[('Excellente', 'Excellente'), ('Positive', 'Positive'), ('Neutre', 'Neutre'), ('Négative', 'Négative'), ('Recherché', 'Recherché')], default='Neutre', max_length=50)),
                ('peopleStatus', models.CharField(choices=[('Excellente', 'Excellente'), ('Positive', 'Positive'), ('Neutre', 'Neutre'), ('Négative', 'Négative'), ('Recherché', 'Recherché')], default='Positive', max_length=50)),
                ('clergyStatus', models.CharField(choices=[('Excellente', 'Excellente'), ('Positive', 'Positive'), ('Neutre', 'Neutre'), ('Négative', 'Négative'), ('Recherché', 'Recherché')], default='Neutre', max_length=50)),
                ('labretStatus', models.CharField(choices=[('Excellente', 'Excellente'), ('Positive', 'Positive'), ('Neutre', 'Neutre'), ('Négative', 'Négative'), ('Recherché', 'Recherché')], default='Positive', max_length=50)),
                ('owner', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='fiches.charactersheet')),
            ],
        ),
        migrations.CreateModel(
            name='ClergyReputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('globalStatus', models.CharField(choices=[('Excellente', 'Excellente'), ('Positive', 'Positive'), ('Neutre', 'Neutre'), ('Négative', 'Négative'), ('Recherché', 'Recherché')], default='Positive', max_length=50)),
                ('kingStatus', models.CharField(choices=[('Excellente', 'Excellente'), ('Positive', 'Positive'), ('Neutre', 'Neutre'), ('Négative', 'Négative'), ('Recherché', 'Recherché')], default='Neutre', max_length=50)),
                ('nobilityStatus', models.CharField(choices=[('Excellente', 'Excellente'), ('Positive', 'Positive'), ('Neutre', 'Neutre'), ('Négative', 'Négative'), ('Recherché', 'Recherché')], default='Positive', max_length=50)),
                ('peopleStatus', models.CharField(choices=[('Excellente', 'Excellente'), ('Positive', 'Positive'), ('Neutre', 'Neutre'), ('Négative', 'Négative'), ('Recherché', 'Recherché')], default='Positive', max_length=50)),
                ('clergyStatus', models.CharField(choices=[('Excellente', 'Excellente'), ('Positive', 'Positive'), ('Neutre', 'Neutre'), ('Négative', 'Négative'), ('Recherché', 'Recherché')], default='Positive', max_length=50)),
                ('labretStatus', models.CharField(choices=[('Excellente', 'Excellente'), ('Positive', 'Positive'), ('Neutre', 'Neutre'), ('Négative', 'Négative'), ('Recherché', 'Recherché')], default='Positive', max_length=50)),
                ('owner', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='fiches.charactersheet')),
            ],
        ),
        migrations.CreateModel(
            name='BanishedReputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('globalStatus', models.CharField(choices=[('Excellente', 'Excellente'), ('Positive', 'Positive'), ('Neutre', 'Neutre'), ('Négative', 'Négative'), ('Recherché', 'Recherché')], default='Négative', max_length=50)),
                ('kingStatus', models.CharField(choices=[('Excellente', 'Excellente'), ('Positive', 'Positive'), ('Neutre', 'Neutre'), ('Négative', 'Négative'), ('Recherché', 'Recherché')], default='Négative', max_length=50)),
                ('nobilityStatus', models.CharField(choices=[('Excellente', 'Excellente'), ('Positive', 'Positive'), ('Neutre', 'Neutre'), ('Négative', 'Négative'), ('Recherché', 'Recherché')], default='Négative', max_length=50)),
                ('peopleStatus', models.CharField(choices=[('Excellente', 'Excellente'), ('Positive', 'Positive'), ('Neutre', 'Neutre'), ('Négative', 'Négative'), ('Recherché', 'Recherché')], default='Négative', max_length=50)),
                ('clergyStatus', models.CharField(choices=[('Excellente', 'Excellente'), ('Positive', 'Positive'), ('Neutre', 'Neutre'), ('Négative', 'Négative'), ('Recherché', 'Recherché')], default='Négative', max_length=50)),
                ('labretStatus', models.CharField(choices=[('Excellente', 'Excellente'), ('Positive', 'Positive'), ('Neutre', 'Neutre'), ('Négative', 'Négative'), ('Recherché', 'Recherché')], default='Négative', max_length=50)),
                ('banishedStatus', models.CharField(choices=[('Excellente', 'Excellente'), ('Positive', 'Positive'), ('Neutre', 'Neutre'), ('Négative', 'Négative'), ('Recherché', 'Recherché')], default='Positive', max_length=50)),
                ('mafiaStatus', models.CharField(choices=[('Excellente', 'Excellente'), ('Positive', 'Positive'), ('Neutre', 'Neutre'), ('Négative', 'Négative'), ('Recherché', 'Recherché')], default='Neutre', max_length=50)),
                ('owner', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='fiches.charactersheet')),
            ],
        ),
    ]
