# Generated by Django 4.0.3 on 2022-04-23 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fiches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonReputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('globalStatus', models.CharField(choices=[('Excellente', 'Excellente'), ('Positive', 'Positive'), ('Neutre', 'Neutre'), ('Négative', 'Négative'), ('Recherché', 'Recherché'), ('Banni(e)', 'Banni(e)')], default='Neutre', max_length=50)),
                ('kingStatus', models.CharField(choices=[('Excellente', 'Excellente'), ('Positive', 'Positive'), ('Neutre', 'Neutre'), ('Négative', 'Négative'), ('Recherché', 'Recherché'), ('Banni(e)', 'Banni(e)')], default='Neutre', max_length=50)),
                ('nobilityStatus', models.CharField(choices=[('Excellente', 'Excellente'), ('Positive', 'Positive'), ('Neutre', 'Neutre'), ('Négative', 'Négative'), ('Recherché', 'Recherché'), ('Banni(e)', 'Banni(e)')], default='Neutre', max_length=50)),
                ('peopleStatus', models.CharField(choices=[('Excellente', 'Excellente'), ('Positive', 'Positive'), ('Neutre', 'Neutre'), ('Négative', 'Négative'), ('Recherché', 'Recherché'), ('Banni(e)', 'Banni(e)')], default='Neutre', max_length=50)),
                ('militiaStatus', models.CharField(choices=[('Excellente', 'Excellente'), ('Positive', 'Positive'), ('Neutre', 'Neutre'), ('Négative', 'Négative'), ('Recherché', 'Recherché'), ('Banni(e)', 'Banni(e)')], default='Neutre', max_length=50)),
                ('clergyStatus', models.CharField(choices=[('Excellente', 'Excellente'), ('Positive', 'Positive'), ('Neutre', 'Neutre'), ('Négative', 'Négative'), ('Recherché', 'Recherché'), ('Banni(e)', 'Banni(e)')], default='Neutre', max_length=50)),
                ('labretStatus', models.CharField(choices=[('Excellente', 'Excellente'), ('Positive', 'Positive'), ('Neutre', 'Neutre'), ('Négative', 'Négative'), ('Recherché', 'Recherché'), ('Banni(e)', 'Banni(e)')], default='Neutre', max_length=50)),
                ('sombreboisStatus', models.CharField(choices=[('Excellente', 'Excellente'), ('Positive', 'Positive'), ('Neutre', 'Neutre'), ('Négative', 'Négative'), ('Recherché', 'Recherché'), ('Banni(e)', 'Banni(e)')], default='Neutre', max_length=50)),
                ('mafiaStatus', models.CharField(choices=[('Excellente', 'Excellente'), ('Positive', 'Positive'), ('Neutre', 'Neutre'), ('Négative', 'Négative'), ('Recherché', 'Recherché'), ('Banni(e)', 'Banni(e)')], default='Neutre', max_length=50)),
                ('banishedStatus', models.CharField(choices=[('Excellente', 'Excellente'), ('Positive', 'Positive'), ('Neutre', 'Neutre'), ('Négative', 'Négative'), ('Recherché', 'Recherché'), ('Banni(e)', 'Banni(e)')], default='Neutre', max_length=50)),
                ('guildStatus', models.CharField(choices=[('Excellente', 'Excellente'), ('Positive', 'Positive'), ('Neutre', 'Neutre'), ('Négative', 'Négative'), ('Recherché', 'Recherché'), ('Banni(e)', 'Banni(e)')], default='Neutre', max_length=50)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fiches.charactersheet')),
            ],
        ),
    ]
