# Generated by Django 4.0.3 on 2022-04-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reputationboard',
            name='group',
            field=models.CharField(blank=True, choices=[('Groupe', 'Groupe'), ('Milice(ne)', 'Milice'), ('Habitant(e)', 'Peuple'), ('Noble', 'Noblesse'), ('Prêtre(sse)', 'Clergé'), ('Banni(e)', 'Bannis')], default='Groupe', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reputationboard',
            name='status',
            field=models.CharField(blank=True, choices=[('Statut', 'Statut'), ('Neutre', 'Neutre'), ('Positive', 'Positive'), ('Négative', 'Négative')], default='Statut', max_length=50, null=True),
        ),
    ]
