# Generated by Django 4.0.3 on 2022-04-24 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reputations', '0005_alter_commonreputation_banishedstatus_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commonreputation',
            options={'ordering': ['owner']},
        ),
    ]
