# Generated by Django 4.1.4 on 2022-12-31 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputations', '0006_alter_commonreputation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonreputation',
            name='flavor_text',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
