# Generated by Django 4.1.4 on 2023-01-12 20:02

from django.db import migrations, models
import utils.reputations


class Migration(migrations.Migration):

    dependencies = [
        ('reputations', '0007_commonreputation_flavor_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonreputation',
            name='flavor_text',
            field=models.JSONField(blank=True, default=utils.reputations.flavor, null=True),
        ),
    ]
