# Generated by Django 4.0.3 on 2022-05-20 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0021_alter_charactersheet_is_active'),
        ('cartes', '0002_alter_card_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fiches.charactersheet'),
        ),
    ]
