# Generated by Django 4.0.3 on 2022-05-20 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartes', '0004_alter_card_options_remove_card_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='avatar',
        ),
    ]
