# Generated by Django 4.1 on 2022-09-10 17:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='backups')),
                ('created', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
