# Generated by Django 4.1 on 2022-09-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0002_alter_snapshot_options_alter_snapshot_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='save',
            field=models.TextField(blank=True, null=True),
        ),
    ]
