# Generated by Django 4.1 on 2022-09-29 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0003_snapshot_save'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snapshot',
            old_name='save',
            new_name='content',
        ),
    ]
