# Generated by Django 4.1 on 2022-09-29 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0004_rename_save_snapshot_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snapshot',
            name='file',
        ),
    ]
