# Generated by Django 4.0.3 on 2022-05-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('succes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_1',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_10',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_11',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_12',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_13',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_14',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_15',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_16',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_17',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_18',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_19',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_2',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_20',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_21',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_22',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_23',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_24',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_25',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_26',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_27',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_28',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_29',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_3',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_30',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_31',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_32',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_33',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_34',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_35',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_36',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_37',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_38',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_39',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_4',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_40',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_41',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_42',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_43',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_44',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_45',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_46',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_47',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_48',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_49',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_5',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_50',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_51',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_52',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_53',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_54',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_55',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_56',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_57',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_58',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_59',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_6',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_60',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_61',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_62',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_63',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_64',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_65',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_66',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_67',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_68',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_69',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_7',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_70',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_71',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_72',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_73',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_74',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_75',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_76',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_77',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_78',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_79',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_8',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_80',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_81',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_82',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_83',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_84',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_85',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_86',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_87',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_88',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_89',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_9',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='achievementssheet',
            name='success_90',
            field=models.CharField(blank=True, choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=50, null=True),
        ),
    ]
