# Generated by Django 4.0.3 on 2022-08-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('succes', '0008_alter_achievementssheet_succes_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.TextField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
