# Generated by Django 4.0.3 on 2022-08-13 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('succes', '0010_rename_name_achievement_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_1',
            new_name='Achat maximum',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_10',
            new_name='Admirateur',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_11',
            new_name='Agent secret',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_12',
            new_name='Animateur',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_13',
            new_name='Attrape moi si tu peux',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_14',
            new_name="Aussi rapide qu'un escargot",
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_15',
            new_name='Bagarreur',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_16',
            new_name='Bienfaiteur',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_17',
            new_name='Boite à idées',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_18',
            new_name='Bon soldat',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_19',
            new_name='Bonne conscience',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_2',
            new_name="C'est qui l'patron?",
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_20',
            new_name='Casse cou',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_21',
            new_name='Citoyen modèle',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_22',
            new_name='Collectionneur de râteaux',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_23',
            new_name='Commentateur ultime',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_24',
            new_name='Connu de tous',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_25',
            new_name='Célébrité',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_26',
            new_name='Dans ma bulle',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_27',
            new_name='Deuxième chance',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_28',
            new_name='Don Jehan',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_29',
            new_name='Duo de choc',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_3',
            new_name='Débutant',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_30',
            new_name='Ennemi de la Chatbox',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_31',
            new_name='Ennemi public',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_32',
            new_name='Ennemi public²',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_33',
            new_name='Entraide maximum',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_34',
            new_name='Essaie encore',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_35',
            new_name="Est-ce que tu m'aimes?",
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_36',
            new_name='Expert aventurier',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_37',
            new_name='Expert du questionnement',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_38',
            new_name='Floodeur',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_39',
            new_name='Guide du Royaume',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_4',
            new_name='Il faut bien commencer',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_40',
            new_name='Influençable',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_41',
            new_name='Insatiable',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_42',
            new_name='Investisseur',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_43',
            new_name="J'ai les bourses pleines!",
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_44',
            new_name='Jamais sans ma poupée',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_45',
            new_name='Jamais sans mes potes',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_46',
            new_name='Jamais trois sans moi',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_47',
            new_name='Je suis un génie',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_48',
            new_name='Je suis une Légende',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_49',
            new_name='Juste pour regarder',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_5',
            new_name='La bête de trop',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_50',
            new_name='La goutte de trop',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_51',
            new_name='La main dans le sac',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_52',
            new_name='Le bon samaritain',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_53',
            new_name='Le goût du risque',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_54',
            new_name='Marginal',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_55',
            new_name='Mauvais endroit au mauvais moment',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_56',
            new_name='Mauvais garçon',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_57',
            new_name='Maîtrise',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_58',
            new_name='Membre connu',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_59',
            new_name='Membre discret',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_6',
            new_name='Membre exemplaire',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_60',
            new_name='Mes précieuses compétences',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_61',
            new_name='Messager',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_62',
            new_name='Mon ami à moi',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_63',
            new_name='Musicothérapie',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_64',
            new_name='Ménage à trois',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_65',
            new_name='Opération infiltration',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_66',
            new_name='Oups',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_67',
            new_name='Partenaire particulier',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_68',
            new_name='Pickpocket',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_69',
            new_name='Pigeon voyageur',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_7',
            new_name='Plume en activité',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_70',
            new_name='Pour la bonne cause',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_71',
            new_name="Pro de l'organisation",
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_72',
            new_name='Pro de la publicité',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_73',
            new_name='Pro des carrières',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_74',
            new_name='Pro des défis',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_75',
            new_name='Que la trinité soit avec moi',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_76',
            new_name='Réputation en herbe',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_77',
            new_name='SOS',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_78',
            new_name='Sexe addict',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_79',
            new_name='Sociable',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_8',
            new_name='Solitaire',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_80',
            new_name='Suicidaire 2.0',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_81',
            new_name='Toi, mon toit',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_82',
            new_name='Tous ensemble',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_83',
            new_name='Traître',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_84',
            new_name='Trouble de la personnalité',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_85',
            new_name='Un pour tous et tous pour moi',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_86',
            new_name='Very bad Brume',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_87',
            new_name='Visiteur',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_88',
            new_name='Volontaire',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_89',
            new_name='À la tienne',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_9',
            new_name='À vendre',
        ),
        migrations.RenameField(
            model_name='achievementssheet',
            old_name='succes_90',
            new_name='Échec critique',
        ),
    ]
