# Generated by Django 4.0.3 on 2022-08-13 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('succes', '0013_achievementssheet_achat maximum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Achat maximum',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Admirateur',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Agent secret',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Animateur',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Attrape moi si tu peux',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name="Aussi rapide qu'un escargot",
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Bagarreur',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Bienfaiteur',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Boite à idées',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Bon soldat',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Bonne conscience',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name="C'est qui l'patron?",
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Casse cou',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Citoyen modèle',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Collectionneur de râteaux',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Commentateur ultime',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Connu de tous',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Célébrité',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Dans ma bulle',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Deuxième chance',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Don Jehan',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Duo de choc',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Débutant',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Ennemi de la Chatbox',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Ennemi public',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Ennemi public²',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Entraide maximum',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Essaie encore',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name="Est-ce que tu m'aimes?",
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Expert aventurier',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Expert du questionnement',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Floodeur',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Guide du Royaume',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Il faut bien commencer',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Influençable',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Insatiable',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Investisseur',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name="J'ai les bourses pleines!",
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Jamais sans ma poupée',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Jamais sans mes potes',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Jamais trois sans moi',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Je suis un génie',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Je suis une Légende',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Juste pour regarder',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='La bête de trop',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='La goutte de trop',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='La main dans le sac',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Le bon samaritain',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Le goût du risque',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Marginal',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Mauvais endroit au mauvais moment',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Mauvais garçon',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Maîtrise',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Membre connu',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Membre discret',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Membre exemplaire',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Mes précieuses compétences',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Messager',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Mon ami à moi',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Musicothérapie',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Ménage à trois',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Opération infiltration',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Oups',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Partenaire particulier',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Pickpocket',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Pigeon voyageur',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Plume en activité',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Pour la bonne cause',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name="Pro de l'organisation",
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Pro de la publicité',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Pro des carrières',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Pro des défis',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Que la trinité soit avec moi',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Réputation en herbe',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='SOS',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Sexe addict',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Sociable',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Solitaire',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Suicidaire 2.0',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Toi, mon toit',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Tous ensemble',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Traître',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Trouble de la personnalité',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Un pour tous et tous pour moi',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Very bad Brume',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Visiteur',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Volontaire',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='À la tienne',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='À vendre',
        ),
        migrations.RemoveField(
            model_name='achievementssheet',
            name='Échec critique',
        ),
    ]
