# Generated by Django 4.0.3 on 2022-08-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('succes', '0014_remove_achievementssheet_achat maximum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievementssheet',
            name='achievement',
            field=models.BooleanField(default=False),
        ),
    ]
