# Generated by Django 4.1 on 2022-09-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('succes', '0017_remove_achievementssheet_achat maximum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievementssheet',
            name='Achat maximum',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Admirateur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Agent secret',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Animateur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Attrape moi si tu peux',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name="Aussi rapide qu'un escargot",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Bagarreur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Bienfaiteur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Boite à idées',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Bon soldat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Bonne conscience',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name="C'est qui l'patron?",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Casse cou',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Citoyen modèle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Collectionneur de râteaux',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Commentateur ultime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Connu de tous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Célébrité',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Dans ma bulle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Deuxième chance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Don Jehan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Duo de choc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Débutant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Ennemi de la Chatbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Ennemi public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Ennemi public²',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Entraide maximum',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Essaie encore',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name="Est-ce que tu m'aimes?",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Expert aventurier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Expert du questionnement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Floodeur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Guide du Royaume',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Il faut bien commencer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Influençable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Insatiable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Investisseur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name="J'ai les bourses pleines!",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Jamais sans ma poupée',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Jamais sans mes potes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Jamais trois sans moi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Je suis un génie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Je suis une Légende',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Juste pour regarder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='La bête de trop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='La goutte de trop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='La main dans le sac',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Le bon samaritain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Le goût du risque',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Marginal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Mauvais endroit au mauvais moment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Mauvais garçon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Maîtrise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Membre connu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Membre discret',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Membre exemplaire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Mes précieuses compétences',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Messager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Mon ami à moi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Musicothérapie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Ménage à trois',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Opération infiltration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Oups',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Partenaire particulier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Pickpocket',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Pigeon voyageur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Plume en activité',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Pour la bonne cause',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name="Pro de l'organisation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Pro de la publicité',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Pro des carrières',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Pro des défis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Que la trinité soit avec moi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Réputation en herbe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='SOS',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Sexe addict',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Sociable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Solitaire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Suicidaire 2.0',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Toi, mon toit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Tous ensemble',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Traître',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Trouble de la personnalité',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Un pour tous et tous pour moi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Very bad Brume',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Visiteur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Volontaire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='À la tienne',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='À vendre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='achievementssheet',
            name='Échec critique',
            field=models.BooleanField(default=False),
        ),
    ]
