# Generated by Django 4.1 on 2022-12-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressbar',
            name='symbol',
            field=models.CharField(default='%', max_length=10),
        ),
        migrations.AddField(
            model_name='progressbar',
            name='total',
            field=models.IntegerField(default=100),
        ),
    ]
