# Generated by Django 4.1 on 2022-09-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chroniques', '0003_remove_chronique_title_alter_chronique_banished_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chronique',
            name='aliases',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
