# Generated by Django 4.1 on 2022-09-16 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chroniques', '0004_chronique_aliases'),
    ]

    operations = [
        migrations.AddField(
            model_name='chronique',
            name='dc',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
