# Generated by Django 4.1 on 2022-12-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chroniques', '0005_chronique_dc'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsChronicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_1', models.TextField(blank=True, null=True)),
                ('item_2', models.TextField(blank=True, null=True)),
                ('item_3', models.TextField(blank=True, null=True)),
                ('item_4', models.TextField(blank=True, null=True)),
                ('item_5', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
