# Generated by Django 4.1 on 2022-12-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chroniques', '0006_newschronicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='newschronicle',
            name='aliases',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='newschronicle',
            name='banished',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='newschronicle',
            name='characters',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='newschronicle',
            name='clergy',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='newschronicle',
            name='dc',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='newschronicle',
            name='militia',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='newschronicle',
            name='nobles',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='newschronicle',
            name='people',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
