# Generated by Django 4.1 on 2022-12-03 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0028_remove_charactersheet_skill_set'),
        ('chroniques', '0007_newschronicle_aliases_newschronicle_banished_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newschronicle',
            name='honor_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fiches.charactersheet'),
        ),
    ]
