# Generated by Django 4.1 on 2022-12-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chroniques', '0008_newschronicle_honor_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='newschronicle',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
