# Generated by Django 4.1 on 2022-12-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chroniques', '0010_newschronicle_new_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='newschronicle',
            name='honor_member_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
